/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;
import java.awt.Component;
import helpers.*;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import java.util.ArrayList;

public class Pizza_Main_Tabbed extends javax.swing.JFrame {

    private PizzaOrder aOrder; 
    private final DefaultListModel<PizzaOrder> listModel;
    
    
    private final DefaultListModel<PizzaOrder> arrayModel;
    
    private final ArrayList<PizzaOrder> myList;
    
    public Pizza_Main_Tabbed() {
        initComponents();
        enableFields(false);
        
        listModel = new DefaultListModel<>();
        lstOrders.setModel(listModel);
        
        arrayModel = new DefaultListModel<>();
        myList = new ArrayList<>();
        lstArray.setModel(arrayModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSize = new javax.swing.ButtonGroup();
        tabPizzaInformation = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        pnlOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlCustomer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        pnlSize = new javax.swing.JPanel();
        radSmall = new javax.swing.JRadioButton();
        radMedium = new javax.swing.JRadioButton();
        radLarge = new javax.swing.JRadioButton();
        pnlToppings = new javax.swing.JPanel();
        chkExtraCheese = new javax.swing.JCheckBox();
        chkSausage = new javax.swing.JCheckBox();
        chkHam = new javax.swing.JCheckBox();
        btnSubmitOrder = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnShowOrderList = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstArray = new javax.swing.JList<PizzaOrder>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArrayDetails = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOrders = new javax.swing.JList<PizzaOrder>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOrderDetails = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mnuNewOrder = new javax.swing.JMenuItem();
        mnuSubmit = new javax.swing.JMenuItem();
        mnuSummary = new javax.swing.JMenu();
        mnuDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Best Pizza Ordering");

        tabPizzaInformation.setForeground(new java.awt.Color(0, 0, 80));
        tabPizzaInformation.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        tabPizzaInformation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPizzaInformationStateChanged(evt);
            }
        });

        pnlOrder.setPreferredSize(new java.awt.Dimension(579, 550));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Please enter your name and select your ordering options:");

        pnlCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel5.setText("First Name:");

        txtFirstName.setToolTipText("Enter your first name");
        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });

        jLabel6.setText("Last Name:");

        txtLastName.setToolTipText("Enter your last name");
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlCustomerLayout = new javax.swing.GroupLayout(pnlCustomer);
        pnlCustomer.setLayout(pnlCustomerLayout);
        pnlCustomerLayout.setHorizontalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirstName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCustomerLayout.setVerticalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlSize.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pizza Size (please select one)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        grpSize.add(radSmall);
        radSmall.setText("Small: $6.99 ");
        radSmall.setToolTipText("Select for small pizza at $6.99");
        radSmall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radSmallItemStateChanged(evt);
            }
        });

        grpSize.add(radMedium);
        radMedium.setText("Medium: $9.99  ");
        radMedium.setToolTipText("Select for medium pizza at $9.99");
        radMedium.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radMediumItemStateChanged(evt);
            }
        });

        grpSize.add(radLarge);
        radLarge.setText("Large: $12.99");
        radLarge.setToolTipText("Select for large pizza at $12.99");
        radLarge.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radLargeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlSizeLayout = new javax.swing.GroupLayout(pnlSize);
        pnlSize.setLayout(pnlSizeLayout);
        pnlSizeLayout.setHorizontalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radMedium)
                    .addComponent(radSmall)
                    .addComponent(radLarge))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        pnlSizeLayout.setVerticalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeLayout.createSequentialGroup()
                .addComponent(radSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radLarge))
        );

        pnlToppings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toppings (Select as many as you like)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        chkExtraCheese.setText("Extra Cheese: $1.50 ");
        chkExtraCheese.setToolTipText("Select to add extra cheese for $1.50");
        chkExtraCheese.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkExtraCheeseItemStateChanged(evt);
            }
        });

        chkSausage.setText("Sausage: $2.25");
        chkSausage.setToolTipText("Check to add Sausage for $2.25");
        chkSausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSausageActionPerformed(evt);
            }
        });

        chkHam.setText("Ham: $2.50");
        chkHam.setToolTipText("Check to add Ham for $2.50");
        chkHam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkHamItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlToppingsLayout = new javax.swing.GroupLayout(pnlToppings);
        pnlToppings.setLayout(pnlToppingsLayout);
        pnlToppingsLayout.setHorizontalGroup(
            pnlToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToppingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkExtraCheese)
                    .addComponent(chkSausage)
                    .addComponent(chkHam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlToppingsLayout.setVerticalGroup(
            pnlToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToppingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkExtraCheese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSausage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHam))
        );

        btnSubmitOrder.setText("Submit Order");
        btnSubmitOrder.setToolTipText("Click to show the order total and order summary, and store the order");
        btnSubmitOrder.setEnabled(false);
        btnSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitOrderActionPerformed(evt);
            }
        });

        btnNewOrder.setText("New Order");
        btnNewOrder.setToolTipText("Click to clear all fields and start a new order.");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlToppings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlToppings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitOrder)
                    .addComponent(btnNewOrder))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabPizzaInformation.addTab("Pizza Order Information", jPanel3);

        btnShowOrderList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnShowOrderList.setForeground(new java.awt.Color(0, 0, 80));
        btnShowOrderList.setText("Show Order List");
        btnShowOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowOrderListActionPerformed(evt);
            }
        });

        lstArray.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstArrayValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstArray);

        txtArrayDetails.setColumns(20);
        txtArrayDetails.setRows(5);
        jScrollPane3.setViewportView(txtArrayDetails);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnShowOrderList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnShowOrderList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tabPizzaInformation.addTab("Order List", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 80));
        jLabel1.setText("Order List");

        lstOrders.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstOrders.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstOrdersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstOrders);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 80));
        jLabel2.setText("Order Details");

        txtOrderDetails.setColumns(20);
        txtOrderDetails.setRows(5);
        jScrollPane2.setViewportView(txtOrderDetails);

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 80));
        btnDelete.setText("Delete Order");
        btnDelete.setToolTipText("Click to delete the selected pizza order");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 80));
        btnUpdate.setText("Update Total");
        btnUpdate.setToolTipText("Click to update the total cost of the order");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtTotal.setToolTipText("Override calculated total price of the order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        tabPizzaInformation.addTab("Order Summary", jPanel1);

        lblWelcome.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 255));
        lblWelcome.setText("Welcome to Best Pizza!");
        lblWelcome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblWelcome.setName("lblWelcome"); // NOI18N

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        mnuFile.setText("File");
        mnuFile.setToolTipText("Click to exit the application");

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setForeground(new java.awt.Color(0, 0, 80));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        mnuBar.add(mnuFile);

        mnuOrder.setText("Pizza Order");

        mnuNewOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mnuNewOrder.setMnemonic('n');
        mnuNewOrder.setText("New order");
        mnuNewOrder.setToolTipText("Click to create a new order");
        mnuNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewOrderActionPerformed(evt);
            }
        });
        mnuOrder.add(mnuNewOrder);

        mnuSubmit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuSubmit.setText("Submit Order");
        mnuSubmit.setToolTipText("Click to submit the order");
        mnuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSubmitActionPerformed(evt);
            }
        });
        mnuOrder.add(mnuSubmit);

        mnuBar.add(mnuOrder);

        mnuSummary.setText("Order Summary");

        mnuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mnuDelete.setText("Delete Order");
        mnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteActionPerformed(evt);
            }
        });
        mnuSummary.add(mnuDelete);

        mnuBar.add(mnuSummary);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPizzaInformation)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(tabPizzaInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitOrder() {
        StringBuilder str = new StringBuilder();
        
        if (aOrder != null) {
            str.append("Order submitted\n");
            str.append (aOrder.getOrderSummary());
            OutputHelpers.showStandardDialog(str.toString(), "Pizza Order Submitted"); 
            listModel.addElement(aOrder);
            myList.add(aOrder);
        }
       
    }
    private void enableFields(boolean enable) {
        for (Component  comp : pnlCustomer.getComponents()) {
            if (comp instanceof JTextField) {
                comp.setEnabled(enable);
                ((JTextField) comp).setText("");
            }
        }
        for (Component comp:pnlToppings.getComponents()) {
            if (comp instanceof JCheckBox) {
                comp.setEnabled(enable);
                ((JCheckBox) comp).setSelected(false);
            }
        }
        for (Component comp:pnlSize.getComponents()) {
            if (comp instanceof JRadioButton) {
                comp.setEnabled(enable);
                if (comp == radLarge) {
                    ((JRadioButton) comp).setSelected(true);
                }
            }
        }
        btnSubmitOrder.setEnabled(enable);
    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ApplicationHelpers.terminateGUIApplication("Best Pizza Ordering");
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        newOrder();
    }//GEN-LAST:event_btnNewOrderActionPerformed
    private void newOrder() {
        aOrder = null;
        enableFields(true);
        aOrder = new PizzaOrder();
    }
    private void btnSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitOrderActionPerformed
        submitOrder();
    }//GEN-LAST:event_btnSubmitOrderActionPerformed

    private void chkHamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkHamItemStateChanged
        if (aOrder != null) {
            if (chkHam.isSelected()) {
                aOrder.setHam(true);
            }
            else {
                aOrder.setHam(false);
            }
        }
    }//GEN-LAST:event_chkHamItemStateChanged

    private void chkSausageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSausageActionPerformed
        if (aOrder != null) {
           if (chkSausage.isSelected()) {
               aOrder.setSausage(true);
           }
           else {
               aOrder.setSausage(false);
           }
        }
    }//GEN-LAST:event_chkSausageActionPerformed

    private void chkExtraCheeseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkExtraCheeseItemStateChanged
        if (aOrder != null) {
           if (chkExtraCheese.isSelected()) {
               aOrder.setCheese(true);
           }
           else {
               aOrder.setCheese(false);
           }
        }
    }//GEN-LAST:event_chkExtraCheeseItemStateChanged

    private void radLargeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radLargeItemStateChanged
        if (aOrder != null && radLarge.isSelected()) {
           aOrder.setPizzaSize(PizzaOrder.Size.Large);
        }
    }//GEN-LAST:event_radLargeItemStateChanged

    private void radMediumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radMediumItemStateChanged
        if(aOrder != null && radMedium.isSelected()) {
            aOrder.setPizzaSize(PizzaOrder.Size.Medium);
        }
    }//GEN-LAST:event_radMediumItemStateChanged

    private void radSmallItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radSmallItemStateChanged
        if (aOrder != null && radSmall.isSelected()) {
            aOrder.setPizzaSize(PizzaOrder.Size.Small);
        }
    }//GEN-LAST:event_radSmallItemStateChanged

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        if (aOrder != null) {
             aOrder.setLastName(txtLastName.getText());
        }
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        if (aOrder != null) {
             aOrder.setFirstName(txtFirstName.getText());
        }   
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       deleteOrder();
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void deleteOrder() {
         int item = lstOrders.getSelectedIndex();
        if (item != -1) {
            int response;
            PizzaOrder theOrder = lstOrders.getSelectedValue();
            String prompt = "Are you sure you want to delete order for: " + theOrder.toString();
            response = OutputHelpers.showOKCancelDiaglog(prompt, "Delete order " + theOrder.toString());
            if (response == JOptionPane.YES_OPTION) {
                listModel.removeElementAt(item);
                txtOrderDetails.setText("");
            }

        }
    }
    private void lstOrdersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstOrdersValueChanged
        showOrderDetails();
    }//GEN-LAST:event_lstOrdersValueChanged
    private void showOrderDetails() {
        PizzaOrder aOrder;
        if (lstOrders.getSelectedIndex() != -1) {
            aOrder = lstOrders.getSelectedValue();
            txtOrderDetails.setText(aOrder.getOrderSummary());
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (aOrder != null) {
            double min = -aOrder.getTotal();
            double max = aOrder.getTotal();
            aOrder.setTotal(InputHelpers.parseDoubleField(txtTotal, "Updated Order Total", min, max));
            txtOrderDetails.setText(aOrder.getOrderSummary());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void mnuNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewOrderActionPerformed
        newOrder();
    }//GEN-LAST:event_mnuNewOrderActionPerformed

    private void mnuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSubmitActionPerformed
        submitOrder();
    }//GEN-LAST:event_mnuSubmitActionPerformed

    private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteActionPerformed
        deleteOrder();
    }//GEN-LAST:event_mnuDeleteActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
         ApplicationHelpers.terminateGUIApplication("Best Pizza Ordering");
    }//GEN-LAST:event_mnuExitActionPerformed

    private void tabPizzaInformationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPizzaInformationStateChanged
         int index = tabPizzaInformation.getSelectedIndex();
        if (index==0) {
            enableOrderMenu(true);
            enableSummaryMenu(false);
        }
        else if (index == 1) {
            enableOrderMenu(false);
            enableSummaryMenu(true);
        }
    }//GEN-LAST:event_tabPizzaInformationStateChanged

    private void btnShowOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowOrderListActionPerformed
        if (!myList.isEmpty()) {
            for(PizzaOrder order : myList) {
                arrayModel.addElement(order);
            }
        }
    }//GEN-LAST:event_btnShowOrderListActionPerformed

    private void lstArrayValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstArrayValueChanged
        showArrayOrderDetails();
    }//GEN-LAST:event_lstArrayValueChanged
    private void showArrayOrderDetails() {
        PizzaOrder aOrder;
        if (lstArray.getSelectedIndex() != -1) {
            aOrder = lstArray.getSelectedValue();
            txtArrayDetails.setText(aOrder.getOrderSummary());
        }
    }
    private void enableOrderMenu(boolean enabled) {
        mnuOrder.setEnabled(enabled);
    }
    private void enableSummaryMenu(boolean enabled) {
        mnuSummary.setEnabled(enabled);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza_Main_Tabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza_Main_Tabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza_Main_Tabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza_Main_Tabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza_Main_Tabbed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnShowOrderList;
    private javax.swing.JButton btnSubmitOrder;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkExtraCheese;
    private javax.swing.JCheckBox chkHam;
    private javax.swing.JCheckBox chkSausage;
    private javax.swing.ButtonGroup grpSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<PizzaOrder> lstArray;
    private javax.swing.JList<PizzaOrder> lstOrders;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuDelete;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuNewOrder;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JMenuItem mnuSubmit;
    private javax.swing.JMenu mnuSummary;
    private javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlSize;
    private javax.swing.JPanel pnlToppings;
    private javax.swing.JRadioButton radLarge;
    private javax.swing.JRadioButton radMedium;
    private javax.swing.JRadioButton radSmall;
    private javax.swing.JTabbedPane tabPizzaInformation;
    private javax.swing.JTextArea txtArrayDetails;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtOrderDetails;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
